import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '@/styles/Home.module.css'


export default function Home() {
  return (
    <>
      <Head>
        <title>OpenDOSM - Price Catcher</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <h1>OpenDOSM - Price Catcher</h1>
        </div>

        <div style={{ width: '100%', display: 'flex', flexDirection: 'row', justifyContent: 'center', alignItems: 'center' }}>
          <Link
            href="/pricecatcher"
            className={styles.card}
            rel="noopener noreferrer"
          >
            <h2>
              PriceCatcher
            </h2>
          </Link>
          <Link
            href="/premises"
            className={styles.card}
            rel="noopener noreferrer"
          >
            <h2>
              Senarai Premis
            </h2>
          </Link>
        </div>
      </main>
    </>
  )
}
